### ISSUE TITLE
keep_zeros not working

### ISSUE THREAD

**Issue by robert1112** [zeicold/pycnnum#6]
Hello 

In the code below, i will get there is no such argument. Is it removed? Thank you.

```
def update_amount_in_chines_word(self):
		if self.amount:
			self.amount_in_chines_word = num2cn(self.amount, traditional=True, capitalize=False, alt_two=False,  keep_zeros=False)
```

**Comment by zeicold** [comment]
Hi There is no error log and I cannot reproduce it at my side. I will close this one since I will remove keep_zeros in the next release and make it effect as True in previous releases.

Example:
```python
num2cn('023232.005184132423423423300', numbering_type=NumberingType.HIGH, alt_two=False, upper=False, traditional=False)
'二万三千二百三十二点零零五一八四一三二四二三四二三四二三三零零'
```
